jira.sgnl.yaml
okta.sgnl.yaml

We support both OAuth2 Client Credentials Flow and API token.

Added bearer auth method to Okta template

---

azure-ad.sgnl.yaml

[sc-13509] Add support for Applications to the Azure AD template

---

okta.sgnl.yaml

Tested in staging with relationship creation:
Sync successful:

Okta: added a path relationship to associate user and groups

---

okta.sgnl.yaml

Okta: add SSWS prefix to AuthToken field

---

azure-ad.sgnl.yaml

- Add devices to AAD template
https://learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0

[sc-14309] Add devices to AAD template

---

scim-2.0.sgnl.yaml
scim.sgnl.yaml

This PR adds the YAML template for the SCIM SoR.

[sc-16771] Add YAML template for SCIM SoR

---

scim-2.0.sgnl.yaml

- Updates the SCIM 2.0 template to use parent relationships instead of Join relationships
This should not be merged until support for handling Parent relationships in this format are supported on the backend and frontend
- Backend: https://github.com/SGNL-ai/sgnl/pull/1735
- Frontend: https://app.shortcut.com/sgnl/story/16909/fe-add-support-for-parent-relationship-type

[sc-16904] Update SCIM to use Parent relationships

---

azure-ad.sgnl.yaml
curity.sgnl.yaml
duo.sgnl.yaml
identitynow.sgnl.yaml
jira.sgnl.yaml
okta.sgnl.yaml
pagerduty.sgnl.yaml
salesforce.sgnl.yaml
scim-2.0.sgnl.yaml
servicenow-csm.sgnl.yaml
servicenow-itsm.sgnl.yaml

Modified templates to add displayName to all relationships.

[sc-19558] Added displayName to all relationships.

---

github.sgnl.yaml

This template has all the github MVP entities without the relationships defined. 
Relationships will be added in this follow-up [PR](https://github.com/SGNL-ai/catalog-sgnl-templates/pull/44) - The follow-up template PR with defined relationships is waiting on the UI changes in this [PR](https://app.shortcut.com/sgnl/story/22363/fe-catalog-defining-relationships-limitations)

[sc-22364] GitHub template part 1

---

azure-ad.sgnl.yaml

Updated Azure AD catalog with new entities and the relationship between them:
- `Role`
- `RoleMember`

[sc-17485] Update catalog for Azure AD

---

salesforce.sgnl.yaml

https://app.shortcut.com/sgnl/story/25188/cleanup-of-sfdc-templates

Salesforce Template Cleanup and Filter Addition

---

servicenow-csm.sgnl.yaml
servicenow-itsm.sgnl.yaml

Tested both templates in SGNL, ingested data for all attributes successfully, no errors.
https://app.shortcut.com/sgnl/story/25184/cleanup-of-snow-templates

mj-snow-filtersandAttributeCleanup

---

jira.sgnl.yaml

https://app.shortcut.com/sgnl/story/25398/production-jira-sor-catalog-template-issue-ingest-errors

Created Fix Versions as a Child Object

---

workday.sgnl.yaml

- Adding fields for worker location (city, state, country)
- Adding field for US Citizenship

Adding field for worker location and US citizenship

---

workday.sgnl.yaml

This PR changes ordered to true for the Workday Catalog.
[sc-24382](https://app.shortcut.com/sgnl/story/24382/workday-adapter-add-ordering-support)

[sc-24382] Update Workday Catalog Ordered Field To True

---

activedirectory.sgnl.yaml

**Description of changes**
**Shortcut story**
[sc-25545](https://app.shortcut.com/sgnl/story/25545/sor-improvements-for-active-directory-adapter)
**Pull request intention**
**Pull request checklist**
**Self identified pull request size**

[sc-25545] Update active-directory catalog

---

aws.sgnl.yaml

**Shortcut story**
[sc-25700](https://app.shortcut.com/sgnl/story/25700/aws-iam-as-an-sor)

[sc-25700] Add catalog for AWS

---

jira.sgnl.yaml

- Updating Jira Issue, indexing `key`

Indexing JIRA Issue - Key

---

github-enterprise-server.sgnl.yaml

This fixes the incorrect default adapter config.

[sc-34494] Fix typo in Github template

---

github-enterprise-server.sgnl.yaml
servicenow-itsm.sgnl.yaml

- Made updates and additions to ServiceNow ITSM
- Made update to GitHub (Repo)
Tested inside new sgnl client.

Adding updates to common attributes used in the field

---

azure-ad.sgnl.yaml

Update Entra SoR template and add entities
- RoleRequest: `RoleAssignmentScheduleRequest`
- GroupRequest: `GroupAssignmentScheduleRequest`
- RoleAssignment: `RoleAssignment`

[sc-33597] Add RoleRequest, GroupRequest, and RoleAssignment to Entra

---

crowdstrike-itp.sgnl.yaml

This PR adds 3 new entities from Endpoint Protection module on the CrowdStrike Platform.
- Device
- Incident
- Detect
See the [story](https://app.shortcut.com/sgnl/story/35793) for more details.

[sc-35793] Add endpoint protection entities to CrowdStrike SoR

---

hashicorp.sgnl.yaml

HashiCorp Boundary SoR with Basic authentication
Boundary entities
- Account 
- Host
- Role
- Scope
- User
- Group
- Target
- Session 
- Credential
No relationships are added.

[sc-43104] Hashicorp Boundary SoR Template

---

crowdstrike.sgnl.yaml
curity.sgnl.yaml
duo.sgnl.yaml
github-enterprise-server.sgnl.yaml
google-workspace.sgnl.yaml
sailpoint-iiq.sgnl.yaml
scim-2.0.sgnl.yaml
workday.sgnl.yaml

Adding parent relationships where applicable.

[sc-47627] Add parent relationships for templates where applicable

---

duo.sgnl.yaml

- Removed duplicate parent relationships
- This bug is preventing DUO from being listed in the UI

Fix DUO duplicate relationships

---

entra-id.sgnl.yaml

Resource info: https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0
Attribute Info: https://learn.microsoft.com/en-us/graph/api/resources/assignedlicense?view=graph-rest-1.0

[sc-60179] Set assignedLabels as a child entity of Group
